<section id="content">
    <section id="wrapper">
        <section id="prod-list">
            <h4>Lista de productos</h4>
            <ul>
            <?php 
                foreach($this->movimientos as $producto)
                {
                    $image = base64_encode( $producto->imagen );
                    $data_uri = ( 'data:' . $producto->mime . ';base64,' . $image );
                    echo "
                      <li class=\"prod-item\">
                        <figure id=\"$producto->id\">
                            <img src='$data_uri' alt='img-$producto->nombre' title=' ' / class=\"img-Prod\">

                            <figcaption>
                                <span class=\"nombre\">$producto->nombre</span> $<span class=\"precio\">".intval($producto->precio)."</span>
			  <a class=\"compra\">Comprar</a>
                            </figcaption>
                        </figure>
                      </li>";
                }
                
             ?>
            </ul>
        </section>        
        <section id="der-wrap">
            
            <section id="prod-select">
                <h4>Tu orden</h4>
                <ul>
                    
                </ul>
            </section>
            <section id="prod-orden">
                <h4>Ordena ya!</h4>
                <p>Total a pagar: $<span id="total">0</span></p>
            </section>
        
        </section>
    </section>
    
</section>
  