<?php echo $this->partial( 'galeria_de_productos_adquirir.phtml', $this->productos ); ?>

<aside id='cuenta'>
    <section>
        <figure>
            <img src='/images/cuenta_logo.png' />
        </figure>

        <h1>Cuenta</h1>
        
        <h2>mesa: #401</h2>
        
        <table>
            <thead>
                <th>#</th>
                <th>Producto</th>
                <th>Precio</th>
            </thead>
            
            <tbody>
                <tr>
                    <td>1x</td>
                    <td>Coca-cola</td>
                    <td>$15.00</td>
                </tr>
                
                <tr>
                    <td>3x</td>
                    <td>Cerveza clara</td>
                    <td>$15.00</td>
                </tr>
                
                <tr id='descuento'>
                    <th colspan='2'>descuento:</th>
                    <td>10%</td>
                <tr>
                
                <tr id='subtotal'>
                    <th colspan='2'>subtotal:</th>
                    <td>$27.00</td>
                <tr>
                
                <tr id='iva'>
                    <th colspan='2'>I.V.A.:</th>
                    <td>$4.32</td>
                <tr>
                
                <tr id='total'>
                    <th colspan='2'>Total:</th>
                    <td>$31.32</td>
                <tr>
            </tbody>
        </table>
    </section>
</aside>
