<section id='productos'>
    <section id='bebidas'>
        <section>
            <figure>
                <img src='/images/producto.jpg' alt='' title='' />
                
                <figcaption>
                    Producto 1
                </figcaption>
            </figure>
            
            <figure>
                <img src='/images/producto.jpg' alt='' title='' />
                
                <figcaption>
                    Producto 2
                </figcaption>
            </figure>
            
            <figure>
                <img src='/images/producto.jpg' alt='' title='' />
                
                <figcaption>
                    Producto 3
                </figcaption>
            </figure>
            
            <figure>
                <img src='/images/producto.jpg' alt='' title='' />
                
                <figcaption>
                    Producto 4
                </figcaption>
            </figure>
        </section>
        
        <nav>
            <ul>
                <li>-atrás</li>
                <li>-adelante</li>
            </ul>
        </nav>
    </section>
</section>
