<section id='productos'>
<?php foreach ( $this->productos as $producto ) : ?>
<?php

$image = $this->displayDbImage(
            $producto->mime,
            $producto->imagen,
            'imagen' . $producto->id,
            null,
            $producto->nombre
);
?>

<figure class='producto' id='producto-<?php echo $producto->id; ?>' title='<?php echo $producto->descripcion; ?>'>
    <div class='windowTop'>
    </div>

    <h1><?php echo $producto->nombre; ?></h1>

    <?php echo $image; ?>

    <p class='precio'>$<?php echo $producto->precio; ?></p>
</figure>

<?php endforeach; ?>
</section>
