<?php
$this->title = 'Borrar usuario';
$this->headTitle( $this->title );
?>
<p>
    No mames! El usuario: '<?php echo $this->usuario['nombre']; ?>' va a morir! 
    Estás seguro de cómo te llamas y porqué estás aquí?
</p>
<form action="<?php echo $this->url( array( 'action'=>'delete' ) ); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->usuario['id']; ?>" />
        <input type="submit" name="borrar" value="Sí" />
        <input type="submit" name="borrar" value="No" />
    </div>
</form>
