<table id="UsuariosTabla" >
    <thead>
        <th>Nombre</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th colspan="2">Comandos</th>
    </thead>

    <tbody>
<?php foreach ( $this->usuarios as $usuario ) : ?>
        <tr>
            <td><?php echo $this->escape($usuario->nombre); ?></td>
            <td><?php echo $this->escape($usuario->email); ?></td>
            <td><?php echo $this->escape($usuario->telefono); ?></td>
            <td>editar</td>
            <td>borrar</td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

