<?php
// get it's configuration file
$sitio = new Zend_Config_Ini( APPLICATION_PATH . '/configs/sitio.ini', APPLICATION_ENV );

?>
<?php $this->placeholder('footer')->captureStart();?>

<!-- Logooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooos -->
<div id="footerLinksLogos">
<?php 
    echo $this->img('/images/html5_logo.png', 
        array(
            'id' => 'logo', 
            'title' => 'HTML5', 
            'alt' => 'HTML5'
        )
    ); 

    echo $this->img('/images/css3-logo-large.png', 
        array(
            'id' => 'logo', 
            'title' => 'CSS3',
            'alt' => 'CSS3')
        );

    echo $this->img('/images/ZendFramework-logo.png', 
        array(
            'id' => 'logo', 
            'title' => 'Powered by: ZendFramework', 
            'alt' => 'Powered by: ZendFramework')
        );

    echo $this->img('/images/gpl3-logo.png', 
        array(
            'id' => 'logo',
            'title' => 'GPLv3 2011', 
            'alt' => 'GPLv3 2011')
    );
?>
</div>
<!-- Logooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooos-->


<div id="footerLinks">
    <small id="footerW3CDoctypeValidator">
        <a href="http://validator.w3.org/check?uri=http://<?php echo $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']; ?>"><?php echo $sitio->doctype; ?></a>
    </small>

    <small> | </small>

    <small id="footerW3CCSSValidator">
        <a href="http://jigsaw.w3.org/css-validator/validator?uri=http://<?php echo $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']; ?>">CSS 3</a>
    </small>

    <small> | </small>

    <small id="footerZendFrameworkVersion">
        <a href="http://zendframework.com/">ZF <?php echo Zend_Version::VERSION; ?></a>
    </small>

    <small> | </small>

    <small id="footerDisclaimer">
        <a href="http://gplv3.fsf.org/">GPLv3 <?php echo date('Y'); ?></a>
    </small>

    <small> | </small>
</div>

<?php $this->placeholder('footer')->captureEnd(); ?>
<?php echo $this->placeholder('footer')->setIndent(12); ?>
