<?php
// get it's configuration file
$sitio = new Zend_Config_Ini( APPLICATION_PATH . '/configs/sitio.ini', APPLICATION_ENV );
?>

<?php $this->placeholder('footer')->captureStart();?>

<!-- Logos -->
<div id="footerLinksLogos">
<img alt="HTML5" src="/images/html5_logo.png">
<img alt="CSS3" src="/images/css3-logo-large.png">
<img alt="Powered by: ZendFramework" src="/images/ZendFramework-logo.png">
<img alt="GPLv3 2011" src="/images/gpl3-logo.png">
</div>

<?php $this->placeholder('footer')->captureEnd(); ?>
<?php echo $this->placeholder('footer')->setIndent(12); ?>
