<?php echo $this->doctype() . "\n"; ?>
<html lang="<?php echo $this->sitio->lang; ?>">
    <head>
        <!-- Meta tags -->
        <meta charset="<?php echo $this->sitio->encoding; ?>" />
<?php echo $this->headMeta() . "\n"; ?>

        <!-- Title -->
<?php echo ucwords( $this->headTitle( $this->getControllerName() ) ) . "\n"; ?>

        <!-- CSS, Feeds y favicon -->
<?php echo $this->headLink() . "\n"; ?>

        <!-- jQuery -->
<?php echo $this->partial( '_jquery.phtml' ); ?>
        
        <!-- Javascript -->
<?php echo $this->headScript() . "\n"; ?>
    </head>
    
     <body>
        <!-- Header container -->
        <header>
<?php echo $this->partial( '_header.phtml' ) . "\n"; ?>

            <hgroup>
                <!-- Login -->
                <div id="Login">
<?php echo $this->LoggedInAs() . "\n"; ?>
                </div>
            
                <!-- Menu container -->
                <nav>
<?php echo $this->partial( '_nav.phtml' ) . "\n"; ?>
                </nav>
            </hgroup>    
        </header>

        <!-- Content container -->
        <div id="Contenido">
            <!-- Section Title -->
            <h1><?php echo $this->getControllerName(); ?></h1>
        
            <!-- Content -->
<?php echo $this->partial( '_contenido.phtml' ) . "\n"; ?>
        </div>

        <!-- Footer container -->
        <footer>
<?php echo $this->partial( '_footer.phtml' ) . "\n"; ?>
        </footer>
    </body>
</html>
